"""Configuration parameters for this example."""

NUM_SIMULATORS = 30
POPULATION_SIZE = 5
OFFSPRING_SIZE = 3
NUM_GENERATIONS = 2
CMAES_NUM_GENERATIONS = 5
CMAES_INITIAL_STD = 0.5
CMAES_BOUNDS = [-1.0, 1.0]
CMAES_POP_SIZE = 5
GRID_SIZE = 22
DATABASE_FILE = "database.sqlite"
NUM_REPETITIONS = 2