"""Configuration parameters for this example."""

NUM_SIMULATORS = 30
POPULATION_SIZE = 5
OFFSPRING_SIZE = 5
NUM_GENERATIONS = 10
CMAES_NUM_GENERATIONS = 5
CMAES_INITIAL_STD = 0.5
CMAES_POP_SIZE = 5
GRID_SIZE = 44
DATABASE_FILE = "Assets/temp_database.sqlite"
NUM_REPETITIONS = 3